stabilityprotocol/stability

- runtime/src/precompiles.rs
I missed to update the native token's metadata.
> fix: updated native token metadata

- node/src/chain_spec.rs
Added ours 5 validators to the validator set.
We want test the networks with multiple validators at the same time.
The genesis config has changed, for apply this change to the chain, we have tu start the blockchain from genesis.
> chore: all nodes are validators in alphanet

- docker/entrypoint.sh
Run docker with archive mode
To be able to request the state of the chain in blocks older than 256 blocks (default config)
> Runs node with docker in archive mode

- docker/Dockerfile
Copy pallets folders into docker
> hot-fix: copy pallets folders into docker

- Cargo.lock
- Cargo.toml
- README.md
- node/Cargo.toml
- node/src/benchmarking.rs
- node/src/chain_spec.rs
- node/src/cli.rs
- node/src/client.rs
- node/src/command.rs
- node/src/eth.rs
- node/src/main.rs
- node/src/rpc/eth.rs
- node/src/rpc/mod.rs
- node/src/service.rs
- pallets/root-controller/Cargo.toml
- precompiles/balances-erc20/Cargo.toml
- precompiles/utils/Cargo.toml
- precompiles/utils/macro/Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
- runtime/src/stability_config.rs
Due to the lifecycle of the Susbtrate releases, this PR bumps the project to the Polkadot 0.9.36.
It also adds some refactoring on the deps.
> Upgrade to Polkadot v0.9.36

- .github/workflows/docker-image.yml
- .gitignore
- docker/Dockerfile
Github action for publishing docker images to Github Container Registry in every push to `main` branch.
> Add container building action

- docker/Dockerfile
I missed to change to repo URL in the previous PR.
> fix: label name in dockerfile

- node/src/chain_spec.rs
Set to `20180427`  the chain ID  for both local and development. 
> update: dev and local chain ids

- node/src/chain_spec.rs
This PR fixes the default code for the testing account, which in the current state doesn't work because the initial `code` is set
> fix: test account with default code

- docker/alphanet/Dockerfile
Fixed missing entrypoint.sh route
> fix: dockerfile route

- runtime/src/stability_config.rs
Fix the function build_block_weights in file stability_config
> fix: build_block_weights

- node/src/chain_spec.rs
- precompiles/balances-erc20/src/mock.rs
- runtime/src/stability_config.rs
> Update testing account

- Cargo.lock
- node/Cargo.toml
- node/src/benchmarking.rs
- node/src/chain_spec.rs
- node/src/client.rs
- node/src/command.rs
- node/src/eth.rs
- node/src/rpc/mod.rs
- node/src/service.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
There was a typo on some pkgs related to `stabilty`.
`stabilty != stability`
> Typo: Stabilty != Stability

- runtime/src/lib.rs
Fix the `is_compatible_fee` api
> fix: decentralized native token

- pallets/token-fee-controller/supported-tokens-manager/README.md
- pallets/token-fee-controller/user-fee-selector/README.md
- pallets/token-fee-controller/validator-fee-selector/README.md
- precompiles/token-fee-controller/fee-token-selector/FeeTokenSelector.sol
- precompiles/token-fee-controller/supported-tokens-manager/SupportedTokensManager.sol
- precompiles/token-fee-controller/validator-fee-selector/ValidatorFeeTokenSelector.sol
Update some documentation for Decentralized Native Token
> Update DNT documentation

- docs/DECENTRALIZED-NATIVE-TOKEN.md
Fix documentation about gas fees
> Fix documentation about gas fees

- docs/DECENTRALIZED-NATIVE-TOKEN.md
- docs/PARAMETERS.md
- runtime/src/lib.rs
- runtime/src/stability_config.rs
Fixed base fee using pallet_base_fee support to ease upcoming upgrades. 
> feat: fixed base fee

- .github/workflows/docker-image.yml
- .github/workflows/test.yml
Updates the GitHub workflows to run faster 
> Workflows now runs on self hosted

- pallets/dnt-fee-controller/src/lib.rs
Update default `FeeVaultAddress` value.
> update: default fee vault address

- primitives/runner/src/lib.rs
Fix dividing problem in Runner tests
> Fix error in Runner tests

- primitives/runner/src/lib.rs
Fix native token transfer gas limit for avoiding gas issues
> Fix native token transfer gas limit

- node/src/chain_spec/mod.rs
Add to the default token a name and a Symbol
> add default token name and symbol

- precompiles/fee-rewards-vault-controller/src/lib.rs
- precompiles/token-fee-controller/supported-tokens-manager/src/lib.rs
- precompiles/token-fee-controller/validator-fee-selector/src/lib.rs
Missing view selectors on some precompiles, throwing invalid execution errors.
> missing precompile::view selectors

- docs/README.md
- docs/TRANSACTION-SORTING.md
Added docs explaing how transaction are sorting in stability
> chore: added docs explaing how transaction are sorting in stability

- pallets/token-fee-controller/user-fee-selector/src/lib.rs
- pallets/token-fee-controller/user-fee-selector/src/tests.rs
Removed `on_finalize` logic since it is not necessary with the new fee system.
> refactor: user fee token updates on hot not at block end

- runtime/src/lib.rs
Added payment to non-evm extrinsics. 
With [Unified Accounts PR](https://github.com/stabilityprotocol/stability/pull/72) there was pending to implement fee management for non-evm extrinsics.
> feat: added fee payment to non-evm extrinics

- precompiles/fee-rewards-vault-controller/Ownable2Step.sol
- precompiles/fee-rewards-vault-controller/src/lib.rs
- precompiles/token-fee-controller/fee-token-selector/src/lib.rs
- precompiles/token-fee-controller/supported-tokens-manager/Ownable2Step.sol
- precompiles/token-fee-controller/supported-tokens-manager/src/lib.rs
- precompiles/token-fee-controller/validator-fee-selector/src/lib.rs
- precompiles/upgrade-runtime-controller/Ownable2Step.sol
- precompiles/upgrade-runtime-controller/src/lib.rs
- precompiles/validator-controller/Ownable2Step.sol
- precompiles/validator-controller/src/lib.rs
Improves Gas handling on precompiles and improve readability
> Precompiles normalization

- node/src/chain_spec/alphanet.rs
Add validator to genesis config in Alphanet
> chore: add validator to genesis

- node/src/chain_spec/alphanet.rs
- pallets/validator-set/src/lib.rs
- pallets/validator-set/src/tests.rs
Fix a bug in the pallet validator-set which does not allow remove a validator from approved list
> Fix validator set remove approved

- Cargo.lock
- stability-rpc/Cargo.toml
- stability-rpc/src/lib.rs
- stability-rpc/src/mock.rs
- stability-rpc/src/tests.rs
> Fix test set in stability RPC

- .github/workflows/build-test.yml
- .github/workflows/docker-image.yml
- .github/workflows/test.yml
> Update GH workflows env var

- precompiles/validator-controller/ValidatorController.sol
- precompiles/validator-controller/src/lib.rs
- precompiles/validator-controller/src/tests.rs
Add a new precompile method for getting the actual validator list
> ValidatorController - get_validator_list X get_active_validator_list

- docs/DECENTRALIZED-NATIVE-TOKEN.md
- docs/README.md
- docs/SPONSORED-TRANSACTIONS.md
- pallets/sponsored-transactions/src/lib.rs
Allow sponsored transactio to be submitted to mempool when nonce is higher than expected 
> Allow sponsored transaction to be submitted to mempool when nonce is higher than expected 

- pallets/dnt-fee-controller/src/mock.rs
- pallets/token-fee-controller/validator-fee-selector/src/lib.rs
- pallets/token-fee-controller/validator-fee-selector/src/tests.rs
- precompiles/token-fee-controller/supported-tokens-manager/src/lib.rs
- precompiles/token-fee-controller/supported-tokens-manager/src/tests.rs
- precompiles/token-fee-controller/validator-fee-selector/src/lib.rs
- precompiles/token-fee-controller/validator-fee-selector/src/mock.rs
- precompiles/token-fee-controller/validator-fee-selector/src/tests.rs
- runtime/src/precompiles.rs
- stability-rpc/src/mock.rs
Make default token & default CR controller updatable
> Make default token & default CR controller updatable

- precompiles/token-fee-controller/supported-tokens-manager/SupportedTokensManager.sol
- precompiles/token-fee-controller/supported-tokens-manager/src/lib.rs
- precompiles/token-fee-controller/validator-fee-selector/ValidatorFeeTokenSelector.sol
- precompiles/token-fee-controller/validator-fee-selector/src/lib.rs
Added getter for default ConversionRate and Fee Token.
> Added view methods to precompiles

- precompiles/utils/macro/tests/precompile.rs
- precompiles/utils/macro/tests/precompile/expand/precompile.expanded.rs
- precompiles/utils/macro/tests/precompile/expand/precompileset.expanded.rs
- rust-toolchain
Fixed expansion test, and update rust version
> fix: fixed expansion test

- docs/GETTING-STARTED.md
- docs/README.md
> chore: adding getting started readme

- node/src/chain_spec/mod.rs
Renamed default token to:
- Stability Gas
- GAS
> Rename default token

- docker/client/entrypoint.sh
- docs/GETTING-STARTED.md
- docs/UNIFIED-ACCOUNTS.md
- node/src/chain_spec/mod.rs
- pallets/validator-set/src/lib.rs
- primitives/core/src/lib.rs
Remove the forgotten stuff from the 'ImOnline' pallet removal
> chore: remove imonline stuff

- docker/client/Dockerfile
`COPY chain-specs` to the docker file
> COPY chain-specs

- docker/client/entrypoint.sh
Added zero tx pool to docker params
> chore: added zero gas tx pool to docker

- docs/PARAMETERS.md
- runtime/src/stability_config.rs
Increased block weight to 8.000.000.000.00 (300M gas)
> Increased block weight to 8 Trillions (300 Millions gas)

- client/authorship/src/authorship.rs
Upgrades ZGT request timeout to 500ms
> feat(ZGT): upgrade timeout to 500ms

- precompiles/fee-rewards-vault-controller/FeeRewardsVaultController.sol
Update precompile interface with the missing event `TransactionFee`
> FeeRewardsVaultController - update interface

- pallets/erc20-manager/src/mock.rs
- pallets/token-fee-controller/supported-tokens-manager/src/mock.rs
- pallets/token-fee-controller/user-fee-selector/src/mock.rs
- pallets/token-fee-controller/validator-fee-selector/src/mock.rs
- precompiles/token-fee-controller/fee-token-selector/src/mock.rs
- precompiles/token-fee-controller/validator-fee-selector/src/mock.rs
- runtime/src/stability_config.rs
- stability-rpc/README.md
> fix: default token config

- Cargo.lock
- pallets/dnt-fee-controller/src/lib.rs
- pallets/fee-rewards-vault/src/lib.rs
- pallets/sponsored-transactions/src/lib.rs
Slowmist problem description:
Amount should be greater than zero, a parameter of zero is waste of gas.
Our response:
Suggested changes applied.
> Save gas for ops. amount = 0 (SlowMist N4)

- runtime/src/lib.rs
Fix evm tracing for eth extrinsic wrapper
> Evm tracing for eth extrinsic wrapper

- docker/client/entrypoint.sh
Please provide a clear and concise description of the changes proposed in this pull request.
> feat(Entrypoint): update rpc-max-response-size

- Cargo.lock
- client/authorship/Cargo.toml
- client/authorship/src/authorship.rs
- pallets/zero-gas-transactions/src/lib.rs
- test-utils/stability-runtime/Cargo.toml
- test-utils/stability-runtime/src/lib.rs
Improved process of adding a zero gas transaction to a block
> Improvement zero gas transaction performance

- docker/README.md
- docs/GETTING-STARTED.md
- docs/UNIFIED-ACCOUNTS.md
Updates doc regarding Testnet and how to generate SEED keys
> doc: SEED generator tool and testnet

- primitives/tools/src/custom_fee.rs
- primitives/transaction-validator/src/lib.rs
> Fix fee calculation

- client/authorship/src/authorship.rs
- docker/README.md
- docker/client/entrypoint.sh
- node/src/service.rs
- node/src/stability.rs
Aadded zero-gas-tx-pool-timeout parameter
> feat: added zero-gas-tx-pool-timeout parameter

- docker/README.md
- docs/GETTING-STARTED.md
- docs/README.md
- precompiles/validator-controller/ValidatorController.sol
- precompiles/validator-controller/src/lib.rs
- precompiles/validator-controller/src/tests.rs
One way to check whether a validator is missing blocks is by using a Validator Controller solidity interface. This interface would allow you to monitor the activities of the validator and identify any instances where they are not producing blocks as expected.
Also adds fixes on the documentation
> Validator Controller solidity interface for checking when validator is missing blocks

- Cargo.lock
- pallets/upgrade-runtime-proposal/src/lib.rs
- pallets/upgrade-runtime-proposal/src/mock.rs
- pallets/upgrade-runtime-proposal/src/tests.rs
- precompiles/upgrade-runtime-controller/Cargo.toml
- precompiles/upgrade-runtime-controller/UpgradeRuntimeController.sol
- precompiles/upgrade-runtime-controller/src/lib.rs
- precompiles/upgrade-runtime-controller/src/mock.rs
- precompiles/upgrade-runtime-controller/src/tests.rs
- runtime/src/lib.rs
- Add members and remove from tech council from evm precompie
- Functions to check current runtime code hash and proposed code hash
> Add members to  tech council from EVM precompile

- runtime/src/lib.rs
Upgrades spec_version to version 1 in order to upgrade the chain
> feat: update spec_version in runtime lib.rs

- Cargo.lock
- Cargo.toml
- client/authorship/Cargo.toml
Adds support to GZIP to ZGT request on Block building for faster transfer time and building time.
> feat(authorship): add gzip compression to zgt request
